# Generated by Django 5.2 on 2025-04-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='raTitular',
            field=models.IntegerField(),
        ),
    ]
