# Generated by Django 5.2 on 2025-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamento_ratitular'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
